/* LABEL BY ZARE — consent-aware GA4 + privacy-conscious first-party analytics */
(function(){
  "use strict";
  const CONSENT_KEY = "lz_privacy_analytics_v1";
  const doNotTrack = navigator.doNotTrack === "1" || window.doNotTrack === "1";
  const productionHost = /(^|\.)labelbyzare\.com$/i.test(location.hostname);
  const gaId = String(window.LZ_ANALYTICS_ID || "");
  let consent = doNotTrack ? "denied" : readConsent();
  let gaLoaded = false, visitorId = "", sessionId = "", geoCache = null;
  let engagementTimer = null, lastTick = Date.now(), pendingVisibleSeconds = 0, started=false;
  window.dataLayer = window.dataLayer || [];
  function readConsent(){try{const v=localStorage.getItem(CONSENT_KEY);return v==="granted"||v==="denied"?v:"unset";}catch(_){return "unset";}}
  function uuid(){if(window.crypto?.randomUUID)return window.crypto.randomUUID();return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==="x"?r:(r&3|8);return v.toString(16);});}
  function safeStorage(storage,key,create){try{let value=storage.getItem(key);if(!value&&create){value=create();storage.setItem(key,value);}return value||"";}catch(_){return create?create():"";}}
  function allowed(){return productionHost&&!doNotTrack&&consent==="granted";}
  function ensureIdentity(){if(!allowed())return false;if(!visitorId)visitorId=safeStorage(localStorage,"lz_analytics_visitor",uuid);if(!sessionId){try{const raw=JSON.parse(sessionStorage.getItem("lz_analytics_session")||"null");if(raw?.id&&Date.now()-Number(raw.lastSeen||0)<30*60*1000)sessionId=raw.id;}catch(_){}if(!sessionId)sessionId=uuid();}touchSession();return Boolean(visitorId&&sessionId);}
  function touchSession(){if(!sessionId)return;try{sessionStorage.setItem("lz_analytics_session",JSON.stringify({id:sessionId,lastSeen:Date.now()}));}catch(_){}}
  function clearAnalyticsStorage(){visitorId="";sessionId="";geoCache=null;try{localStorage.removeItem("lz_analytics_visitor");sessionStorage.removeItem("lz_analytics_session");sessionStorage.removeItem("lz_analytics_geo");}catch(_){}}
  function setConsent(value){consent=value==="granted"?"granted":"denied";try{localStorage.setItem(CONSENT_KEY,consent);}catch(_){}if(consent==="denied"){if(window.gtag)gtag("consent","update",{analytics_storage:"denied",ad_storage:"denied",ad_user_data:"denied",ad_personalization:"denied"});clearAnalyticsStorage();}else if(window.gtag)gtag("consent","update",{analytics_storage:"granted",ad_storage:"denied",ad_user_data:"denied",ad_personalization:"denied"});updateConsentUI();if(consent==="granted")startAnalytics(true);else stopEngagement();window.dispatchEvent(new CustomEvent("lz:privacy-consent",{detail:{analytics:consent}}));}
  function loadGA(){if(gaLoaded||!allowed()||!/^G-[A-Z0-9]+$/.test(gaId))return;gaLoaded=true;window.gtag=window.gtag||function(){window.dataLayer.push(arguments);};gtag("js",new Date());gtag("config",gaId,{send_page_view:true,page_location:location.origin+location.pathname,anonymize_ip:true,allow_google_signals:false,allow_ad_personalization_signals:false});const script=document.createElement("script");script.async=true;script.src="https://www.googletagmanager.com/gtag/js?id="+encodeURIComponent(gaId);document.head.appendChild(script);}
  const params=new URLSearchParams(location.search);
  function referrerHost(){try{if(!document.referrer)return"";const u=new URL(document.referrer);if(u.hostname===location.hostname)return"";return u.hostname.replace(/^www\./i,"").slice(0,120);}catch(_){return"";}}
  function deviceInfo(){const ua=navigator.userAgent||"",mobile=/Mobi|Android|iPhone|iPod/i.test(ua),tablet=/iPad|Tablet/i.test(ua);const device=tablet?"Tablet":mobile?"Mobile":"Desktop";let browser="Other";if(/Edg\//.test(ua))browser="Edge";else if(/SamsungBrowser\//.test(ua))browser="Samsung Internet";else if(/Firefox\//.test(ua))browser="Firefox";else if(/Chrome\//.test(ua)&&!/Edg\//.test(ua))browser="Chrome";else if(/Safari\//.test(ua)&&!/Chrome\//.test(ua))browser="Safari";let os="Other";if(/Windows NT/i.test(ua))os="Windows";else if(/Android/i.test(ua))os="Android";else if(/iPhone|iPad|iPod/i.test(ua))os="iOS";else if(/Mac OS X/i.test(ua))os="macOS";else if(/Linux/i.test(ua))os="Linux";return{device,browser,os};}
  const device=deviceInfo(),acquisition={referrer:referrerHost(),source:(params.get("utm_source")||"").slice(0,120),medium:(params.get("utm_medium")||"").slice(0,120),campaign:(params.get("utm_campaign")||"").slice(0,160)};
  function ensureGeo(){if(!allowed())return Promise.resolve({code:"",name:"Unknown",city:"",region:""});if(geoCache)return Promise.resolve(geoCache);try{const saved=JSON.parse(sessionStorage.getItem("lz_analytics_geo")||"null");if(saved?.name){geoCache=saved;return Promise.resolve(saved);}}catch(_){}return fetch("/api/visitor-geo",{headers:{accept:"application/json"},cache:"no-store"}).then(r=>r.ok?r.json():null).then(data=>{geoCache={code:String(data?.countryCode||"").slice(0,3),name:String(data?.countryName||"Unknown").slice(0,80),city:String(data?.city||"").slice(0,100),region:String(data?.region||"").slice(0,100)};try{sessionStorage.setItem("lz_analytics_geo",JSON.stringify(geoCache));}catch(_){}return geoCache;}).catch(()=>geoCache={code:"",name:"Unknown",city:"",region:""});}
  function item(p,quantity=1,size,color){let category="";try{category=window.LZCollections?.forProduct?.(p)?.name||p.category||"";}catch(_){category=p.category||"";}return{item_id:p.id,item_name:p.name,item_brand:"Label by Zare",item_category:category,item_variant:[size,color].filter(Boolean).join(" / "),price:Number(p.price||0),quantity:Number(quantity||1)};}
  async function sendFirstParty(eventName,options={}){if(!allowed()||!window.supabaseClient?.rpc||!ensureIdentity())return;touchSession();const geo=await ensureGeo();const metadata=options.metadata&&typeof options.metadata==="object"?{...options.metadata}:{};if(geo.city||geo.region)metadata.geo={city:geo.city||"",region:geo.region||""};const payload={p_session_id:sessionId,p_visitor_id:visitorId,p_event_type:String(eventName||"").slice(0,40),p_path:String(options.path||location.pathname||"/").slice(0,240),p_page_title:String(document.title||"").slice(0,180),p_product_id:options.productId?String(options.productId).slice(0,120):null,p_product_name:null,p_value:null,p_active_seconds:Math.max(0,Math.min(120,Math.round(Number(options.activeSeconds)||0))),p_country_code:geo.code||null,p_country_name:geo.name||"Unknown",p_device_type:device.device,p_browser:device.browser,p_os:device.os,p_referrer_host:acquisition.referrer||null,p_utm_source:acquisition.source||null,p_utm_medium:acquisition.medium||null,p_utm_campaign:acquisition.campaign||null,p_metadata:metadata};try{await window.supabaseClient.rpc("track_store_analytics",payload);}catch(_){}}
  function firstPartyEcommerce(name,ecommerce={}){if(!allowed())return;const items=Array.isArray(ecommerce.items)?ecommerce.items:[],meta={};if(items.length)meta.item_count=items.reduce((s,x)=>s+Math.max(1,Number(x.quantity)||1),0);if(name==="purchase"||name==="purchase_item")return;if(name==="begin_checkout"){sendFirstParty("begin_checkout",{metadata:meta});return;}if(["view_item","add_to_cart","add_to_wishlist","remove_from_wishlist"].includes(name)){if(!items.length){sendFirstParty(name,{metadata:meta});return;}items.forEach(row=>sendFirstParty(name,{productId:row.item_id,metadata:{...meta,quantity:Number(row.quantity)||1,variant:String(row.item_variant||"").slice(0,120)}}));return;}sendFirstParty(name,{metadata:meta});}
  function track(name,ecommerce={}){if(!allowed())return;window.dataLayer.push({ecommerce:null});window.dataLayer.push({event:name,ecommerce:{currency:"PKR",...ecommerce}});if(gaLoaded&&window.gtag)gtag("event",name,{currency:"PKR",...ecommerce});firstPartyEcommerce(name,ecommerce);}
  function accumulate(){const now=Date.now(),delta=Math.max(0,Math.min(60,(now-lastTick)/1000));if(document.visibilityState==="visible")pendingVisibleSeconds+=delta;lastTick=now;}
  function flushEngagement(){if(!allowed())return;accumulate();const seconds=Math.floor(pendingVisibleSeconds);if(seconds<1)return;pendingVisibleSeconds-=seconds;sendFirstParty("engagement",{activeSeconds:seconds});}
  function startEngagement(){if(engagementTimer||!allowed())return;lastTick=Date.now();engagementTimer=setInterval(flushEngagement,30000);}
  function stopEngagement(){if(engagementTimer){clearInterval(engagementTimer);engagementTimer=null;}pendingVisibleSeconds=0;}
  function context(){return allowed()&&ensureIdentity()?{sessionId,visitorId,consent:"granted"}:{sessionId:"",visitorId:"",consent};}
  window.LZAnalytics={item,track,sendFirstParty,context,get consent(){return consent;},setConsent,firstPartyEnabled:()=>allowed()};
  window.LZPrivacy={get analytics(){return consent;},allowAnalytics:()=>setConsent("granted"),disableAnalytics:()=>setConsent("denied"),reset:()=>{try{localStorage.removeItem(CONSENT_KEY);}catch(_){}consent=doNotTrack?"denied":"unset";clearAnalyticsStorage();updateConsentUI();}};
  function consentBanner(){if(doNotTrack||consent!=="unset"||document.getElementById("lz-consent-banner"))return;const el=document.createElement("section");el.id="lz-consent-banner";el.className="lz-consent";el.setAttribute("role","dialog");el.setAttribute("aria-label","Analytics privacy choices");el.innerHTML='<div><strong>Privacy choices</strong><p>We use optional analytics to understand visits and improve the store. Essential shopping functions work without analytics.</p></div><div class="lz-consent-actions"><button type="button" class="btn btn-outline btn-sm" data-lz-consent="denied">Essential only</button><button type="button" class="btn btn-solid btn-sm" data-lz-consent="granted">Allow analytics</button><a href="/privacy" class="link-underline">Privacy details</a></div>';el.addEventListener("click",e=>{const b=e.target.closest("[data-lz-consent]");if(b)setConsent(b.dataset.lzConsent);});document.body.appendChild(el);}
  function updateConsentUI(){document.getElementById("lz-consent-banner")?.remove();document.querySelectorAll("[data-privacy-status]").forEach(el=>el.textContent=consent==="granted"?"Analytics allowed":consent==="denied"?"Essential only":"No choice saved");}
  function pageAndProductSignals(){if(!allowed())return;sendFirstParty("page_view");(window.PRODUCTS_READY||Promise.resolve()).then(()=>{if(location.pathname.startsWith("/product/")||/product\.html$/i.test(location.pathname)){let productId=null;try{productId=typeof getProductIdFromLocation==="function"?getProductIdFromLocation():params.get("id");}catch(_){productId=params.get("id");}const p=window.PRODUCTS?.find(p=>String(p.id)===String(productId));if(p)track("view_item",{value:p.price,items:[item(p)]});}}).catch(()=>{});}
  function startAnalytics(sendInitial=false){if(!allowed())return;ensureIdentity();ensureGeo();loadGA();startEngagement();if(sendInitial&&!started){started=true;pageAndProductSignals();}}
  document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="hidden")flushEngagement();else lastTick=Date.now();});window.addEventListener("pagehide",flushEngagement,{capture:true});
  document.addEventListener("DOMContentLoaded",()=>{updateConsentUI();document.querySelectorAll('[data-privacy-choice="allow"]').forEach(b=>b.addEventListener("click",()=>setConsent("granted")));document.querySelectorAll('[data-privacy-choice="deny"]').forEach(b=>b.addEventListener("click",()=>setConsent("denied")));if(consent==="granted")startAnalytics(true);else consentBanner();});
})();
