/* One normalization contract for initial HTML, browser hydration and feeds. */
(function(root){const SITE="https://labelbyzare.com";const images=root.LZImageManifest || (typeof module==="object"?require("./image-manifest"):{});const core={site:SITE,escape(value){return String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));},json(value){return JSON.stringify(value).replace(/</g,"\\u003c").replace(/\u2028/g,"\\u2028").replace(/\u2029/g,"\\u2029");},image(value){if(typeof value!=="string"||!value.trim())return"";try{const url=new URL(value.trim(),SITE+"/");return["https:","http:"].includes(url.protocol)?url.href:"";}catch{return"";}},imageSources(value,widths=[480,832,1248]){
 const url=core.image(value);let entries=images[url];
 if(!entries){try{const u=new URL(url);if(u.origin==='https://ldpzgtjbnbdsggaqmuvs.supabase.co' && /^\/storage\/v1\/object\/public\/product-images\/optimized\/[a-z0-9-]+\/original\.(?:jpg|jpeg|png|webp|avif)$/.test(u.pathname)){
 const available=(u.searchParams.get('lz-widths')||'').split(',').map(Number).filter(w=>Number.isInteger(w)&&w>0&&w<=1248);entries={};for(const w of available){const derivative=new URL(u);derivative.search='';derivative.pathname=derivative.pathname.replace(/original\.[^.]+$/,w+'.webp');entries[w]=derivative.href;}
 }}catch{}}
 if(!entries)return [];
 const available=Object.keys(entries).map(Number).filter(w=>w>0).sort((a,b)=>a-b), selected=new Set();
 for(const width of widths){const w=available.find(w=>w>=width)||available.at(-1);if(w)selected.add(w);}
 return [...selected].sort((a,b)=>a-b).map(w=>({width:w,url:entries[w]}));
 },responsive(value,sizes='(max-width:640px) 50vw, (max-width:1024px) 33vw, 25vw',widths){const sources=core.imageSources(value,widths);return sources.length?'srcset="'+core.escape(sources.map(s=>s.url+' '+s.width+'w').join(', '))+'" sizes="'+core.escape(sizes)+'"':'';},setImage(img,value,sizes='(max-width:1080px) 100vw, 55vw'){
 const sources=core.imageSources(value);img.removeAttribute('srcset');img.removeAttribute('sizes');
 if(sources.length){img.sizes=sizes;img.srcset=sources.map(s=>s.url+' '+s.width+'w').join(', ');}img.src=core.image(value);
 },selection(p,query={}){const n=core.normalize(p);const get=key=>query instanceof URLSearchParams?query.get(key):query[key];return{size:n.sizes.includes(get('size'))?get('size'):n.sizes[0],color:n.colors.some(c=>c.name===get('color'))?get('color'):n.colors[0].name};},sizeUrl(p,size){const n=core.normalize(p);return core.productUrl(n)+(n.sizes.length>1?'?size='+encodeURIComponent(n.sizes.includes(size)?size:n.sizes[0]):'');},slug(value){return String(value||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,60)||"abaya";},productUrl(p){return p?.id?`/product/${core.slug(p.name)}/${encodeURIComponent(p.id)}`:"/shop";},productLabel(p){const name=String(p?.name||'Label by Zare piece').trim(),category=String(p?.category||'').trim(),type=/^shawls?$/i.test(category)?'Shawl':/^kaftan$/i.test(category)?'Kaftan':'Abaya';return /\b(?:abayas?|kaftans?|shawls?)\b/i.test(name)?name:`${name} ${type}`;},productTitle(p){return`${core.productLabel(p)} | Label by Zare`;},imageAlt(p,index=0){return core.productLabel(p)+(index>0?` — photograph ${index+1}`:'');},stocked(p){return!!p&&p.in_stock!==false&&p.inStock!==false&&p.discontinued!==true;},normalize(p){const images=[...new Set([p.img,p.img2,...(Array.isArray(p.gallery)?p.gallery:[])].map(core.image).filter(Boolean))],price=Number(p.price),oldPrice=Number(p.old_price??p.oldPrice);return{...p,id:String(p.id),name:String(p.name||"Label by Zare piece"),category:String(p.category||"Everyday"),price:Number.isFinite(price)&&price>0?price:0,oldPrice:(p.is_sale??p.isSale)===true&&Number.isFinite(oldPrice)&&oldPrice>price?oldPrice:null,isSale:(p.is_sale??p.isSale)===true&&oldPrice>price,isNew:(p.is_new??p.isNew)===true,isFeatured:(p.is_featured??p.isFeatured)===true,isBestseller:(p.is_bestseller??p.isBestseller)===true,inStock:core.stocked(p)&&Number.isFinite(price)&&price>0,img:images[0]||"",img2:images[1]||images[0]||"",gallery:images,sizes:Array.isArray(p.sizes)&&p.sizes.length?p.sizes.map(String):["One Size"],colors:Array.isArray(p.colors)&&p.colors.length?p.colors.map(c=>({name:String(typeof c==='string'?c:c.name||'Default'),hex:typeof c==='object'&&/^#[0-9a-f]{3,8}$/i.test(c.hex)?c.hex:'#c2b09c'})):[{name:"Default",hex:"#c2b09c"}],description:String(p.description||""),fabric:String(p.fabric||""),shipping:String(p.shipping||""),returns:String(p.returns||"")};},money(value){return"PKR "+Number(value||0).toLocaleString("en-PK");}};if(typeof module==="object"&&module.exports)module.exports=core;else root.LZCatalog=core;})(typeof window!=="undefined"?window:this);
