(function(root){
  const collections = [
    {heading:"Abayas Online in Pakistan",description:"Shop abayas online in Pakistan. Explore colours and silhouettes, compare prices in PKR, and check fabric details and available sizes at Label by Zare.",slug:"abayas",name:"Abayas",title:"Buy Abayas Online in Pakistan | Label by Zare",type:"abayas",intro:"Explore everyday abayas, occasion pieces, kaftan silhouettes and prayer wear. Find the cut, colour and details that feel right for your wardrobe.",guide:"choosing-an-abaya",advice:"Compare the garment measurements, fabric notes and included pieces on each product page before choosing your size."},
    {heading:"Everyday & Casual Abayas",description:"Explore everyday and casual abayas for your daily wardrobe. Compare colours, fabric details and available sizes, with delivery across Pakistan.",slug:"everyday-abayas",name:"Everyday Abayas",title:"Everyday & Casual Abayas in Pakistan | Label by Zare",type:"abayas",category:"Everyday",intro:"Considered pieces for the everyday wardrobe. Explore simple silhouettes and thoughtful details, with prices, available sizes and fabric information close at hand.",guide:"everyday-abaya-guide",advice:"For regular wear, look at the cut, sleeve shape, lining and care instructions together. Choose a length that works with the shoes you usually wear."},
    {heading:"Occasion & Evening Abayas",description:"Explore occasion abayas for Eid, dinners and celebrations. Compare the available silhouettes, garment details and sizes at Label by Zare.",slug:"occasion-abayas",name:"Occasion Abayas",title:"Occasion & Evening Abayas in Pakistan | Label by Zare",type:"abayas",category:"Occasion",intro:"Abayas for evenings, celebrations and moments worth dressing for. Explore the current occasion edit and take a closer look at each piece’s finish and silhouette.",guide:"occasion-abaya-styling",advice:"Look closely at the actual fabric and trim photographs. Check the delivery information before ordering for a particular date."},
    {heading:"Kaftan Abayas",description:"Shop kaftan abayas at Label by Zare. Explore relaxed silhouettes, compare measurements and available colours, and find a piece for your wardrobe.",slug:"kaftans",name:"Kaftans",title:"Kaftan Abayas Online in Pakistan | Label by Zare",type:"abayas",category:"Kaftan",intro:"Fluid silhouettes, considered together. Discover the Label by Zare kaftan edit, with individual fabric details and measurements to help you choose.",guide:"kaftan-fit-guide",advice:"A relaxed silhouette still needs the right measurements. Compare length, sleeve shape and body width instead of relying on a size label alone."},
    {heading:"Prayer Abayas",description:"Explore prayer abayas at Label by Zare. Compare coverage, measurements, fabric and included pieces, and order for delivery across Pakistan.",slug:"prayer-abayas",name:"Prayer Abayas",title:"Prayer Abayas Online in Pakistan | Label by Zare",type:"abayas",category:"Prayer",intro:"Explore our prayer edit and choose the length, fit and coverage that suit your own preferences. Read each piece’s measurements and included-item details before ordering.",guide:"prayer-abaya-guide",advice:"Check neckline, sleeves and length for your preferred coverage, including when moving. Product details and photographs help you assess each design."},
    {heading:"Shawls Online in Pakistan",description:"Explore shawls at Label by Zare. Compare colours, dimensions and care details to find a finishing piece for your wardrobe, with delivery across Pakistan.",slug:"shawls",name:"Shawls",title:"Shawls Online in Pakistan | Label by Zare",type:"shawls",intro:"A considered finishing touch. Explore the shawl edit and pair your chosen piece with the abayas and kaftans already in your wardrobe.",guide:"shawl-pairing-guide",advice:"Compare colour, dimensions and care details. A styled photograph does not mean the accompanying abaya is included; check the product description."}
  ];
  const api = {
    all:collections,
    get(slug){ return collections.find(c => c.slug === slug); },
    forProduct(p){ return collections.find(c => c.category && c.category.toLowerCase() === String(p.category || "").toLowerCase()) || collections.find(c => c.slug === (/^shawls?$/i.test(p.category || "") ? "shawls" : "abayas")); },
    matches(p,c){ const type=/^shawls?$/i.test(String(p.category || "").trim()) ? "shawls" : "abayas";return type === c.type && (!c.category || String(p.category).toLowerCase() === c.category.toLowerCase()); },
    url(c){ return `/collections/${typeof c === "string" ? c : c.slug}/`; }
  };
  if(typeof module === "object" && module.exports) module.exports = api;
  else root.LZCollections = api;
})(typeof window !== "undefined" ? window : this);
