import homePageModule from '../server/routes/home-page.js';
import collectionPageModule from '../server/routes/collection-page.js';
import journalPageModule from '../server/routes/journal-page.js';
import productPageModule from '../server/routes/product-page.js';
import productFeedModule from '../server/routes/product-feed.js';
import sitemapHtmlModule from '../server/routes/sitemap-html.js';
import sitemapPagesModule from '../server/routes/sitemap-pages.js';
import sitemapProductsModule from '../server/routes/sitemap-products.js';

const homePage=homePageModule.handler,collectionPage=collectionPageModule.handler,journalPage=journalPageModule.handler,productPage=productPageModule.handler,productFeed=productFeedModule.handler,sitemapHtml=sitemapHtmlModule.handler,sitemapPages=sitemapPagesModule.handler,sitemapProducts=sitemapProductsModule.handler;
const SECURITY={'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','X-Frame-Options':'SAMEORIGIN','Permissions-Policy':'camera=(), microphone=(), geolocation=()'};
const COOKIE_UI='<script src="/js/cookie-preferences.js?v=20260908-v29c"></script>';
const ESSENTIAL_VIEW='<script src="/js/essential-pageview.js?v=20260908-v29d"></script>';
function queryObject(url){const out={};for(const [k,v] of url.searchParams)out[k]=v;return out;}
function routeEvent(request){const url=new URL(request.url);return{path:url.pathname,rawPath:url.pathname,rawQuery:url.search.slice(1),rawUrl:url.href,httpMethod:request.method,headers:Object.fromEntries(request.headers),queryStringParameters:queryObject(url),body:null,isBase64Encoded:false};}
function countryName(code){if(!code||code.length!==2)return'Unknown';try{return new Intl.DisplayNames(['en'],{type:'region'}).of(code.toUpperCase())||code.toUpperCase();}catch{return code.toUpperCase();}}
function visitorGeo(request){const cf=request.cf||{},code=String(cf.country||request.headers.get('CF-IPCountry')||'').toUpperCase();const clean=(v,n=100)=>String(v??'').trim().slice(0,n);return new Response(JSON.stringify({countryCode:code,countryName:countryName(code),city:clean(cf.city),region:clean(cf.region||cf.regionCode)}),{status:200,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store, max-age=0','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}});}
function preview(request){try{return new URL(request.url).hostname.endsWith('.workers.dev');}catch{return false;}}
function htmlHarden(body){let html=String(body||'').replace(/@supabase\/supabase-js@2(?=["'])/g,'@supabase/supabase-js@2.105.0').replace(/\/js\/catalog-core\.js\?v=[^"']+/g,'/js/catalog-core.js?v=20260908-v29').replace(/\/js\/analytics\.js\?v=[^"']+/g,'/js/analytics.js?v=20260908-v29');if(!html.includes('v29-hardening.css'))html=html.replace('</head>','<link rel="stylesheet" href="/css/v29-hardening.css?v=20260908-v29"></head>');if(html.includes('class="site-footer"')&&!html.includes('class="footer-legal"'))html=html.replace('</footer>','<span class="footer-legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/shipping-policy">Shipping</a><a href="/returns-policy">Returns</a></span></footer>');if(!html.includes('/js/essential-pageview.js')){if(html.includes('/supabase-client.js'))html=html.replace(/(<script[^>]+src=["']\/supabase-client\.js[^>]*><\/script>)/i,'$1'+ESSENTIAL_VIEW);else html=html.replace('</body>',ESSENTIAL_VIEW+'</body>');}if(!html.includes('/js/cookie-preferences.js'))html=html.replace('</body>',COOKIE_UI+'</body>');return html;}
function fromRouteResult(result,request){const status=Number(result?.statusCode)||200,headers=new Headers(result?.headers||{});for(const [k,v] of Object.entries(SECURITY))if(!headers.has(k))headers.set(k,v);if(preview(request))headers.set('X-Robots-Tag','noindex, nofollow');let body=result?.body??'';if(headers.get('Content-Type')?.includes('text/html'))body=htmlHarden(body);if(request.method==='HEAD')body=null;return new Response(body,{status,headers});}
async function run(handler,request){try{return fromRouteResult(await handler(routeEvent(request)),request);}catch(error){console.error('Label by Zare Worker route failed:',error?.stack||error);return new Response('Service temporarily unavailable.',{status:503,headers:{...SECURITY,'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','Retry-After':'60'}});}}
function redirect(location,status=301){return new Response(null,{status,headers:{Location:location}});}
export default{async fetch(request,env){const url=new URL(request.url),path=url.pathname;if(!['GET','HEAD'].includes(request.method)){if(path==='/api/visitor-geo')return new Response('Method Not Allowed',{status:405,headers:{Allow:'GET, HEAD'}});return env.ASSETS.fetch(request);}if(path==='/api/visitor-geo')return visitorGeo(request);if(path==='/')return run(homePage,request);if(path==='/index.html')return redirect('/');if(path==='/shop'||path==='/sale'||path==='/new-arrivals'||path==='/search'||path.startsWith('/collections/'))return run(collectionPage,request);if(path==='/journal'||path==='/journal/'||path.startsWith('/journal/'))return run(journalPage,request);if(path==='/product'||path==='/product.html'||path.startsWith('/product/'))return run(productPage,request);if(path==='/sitemap-pages.xml')return run(sitemapPages,request);if(path==='/sitemap-products.xml')return run(sitemapProducts,request);if(path==='/sitemap.html')return run(sitemapHtml,request);if(path==='/product-feed.xml')return run(productFeed,request);return env.ASSETS.fetch(request);}};
