import hardenHtml from '../scripts/html-hardening.js';
import { publicDocument } from './public-cache.mjs';
import homePageModule from '../server/routes/home-page.js';
import collectionPageModule from '../server/routes/collection-page.js';
import journalPageModule from '../server/routes/journal-page.js';
import productPageModule from '../server/routes/product-page.js';
import productFeedModule from '../server/routes/product-feed.js';
import sitemapHtmlModule from '../server/routes/sitemap-html.js';
import sitemapPagesModule from '../server/routes/sitemap-pages.js';
import sitemapProductsModule from '../server/routes/sitemap-products.js';

const homePage=homePageModule.handler,collectionPage=collectionPageModule.handler,journalPage=journalPageModule.handler,productPage=productPageModule.handler,productFeed=productFeedModule.handler,sitemapHtml=sitemapHtmlModule.handler,sitemapPages=sitemapPagesModule.handler,sitemapProducts=sitemapProductsModule.handler;
const SECURITY={'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','X-Frame-Options':'SAMEORIGIN','Permissions-Policy':'camera=(), microphone=(), geolocation=()'};
function queryObject(url){const out={};for(const [k,v] of url.searchParams)out[k]=v;return out;}
function routeEvent(request){const url=new URL(request.url);return{path:url.pathname,rawPath:url.pathname,rawQuery:url.search.slice(1),rawUrl:url.href,httpMethod:request.method,headers:Object.fromEntries(request.headers),queryStringParameters:queryObject(url),body:null,isBase64Encoded:false};}
function countryName(code){if(!code||code.length!==2)return'Unknown';try{return new Intl.DisplayNames(['en'],{type:'region'}).of(code.toUpperCase())||code.toUpperCase();}catch{return code.toUpperCase();}}
function visitorGeo(request){const cf=request.cf||{},code=String(cf.country||request.headers.get('CF-IPCountry')||'').toUpperCase();const clean=(v,n=100)=>String(v??'').trim().slice(0,n);return new Response(JSON.stringify({countryCode:code,countryName:countryName(code),city:clean(cf.city),region:clean(cf.region||cf.regionCode)}),{status:200,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, no-store, max-age=0','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}});}
function preview(request){try{return new URL(request.url).hostname.endsWith('.workers.dev');}catch{return false;}}
function fromRouteResult(result,request){const status=Number(result?.statusCode)||200,headers=new Headers(result?.headers||{});for(const [k,v] of Object.entries(SECURITY))if(!headers.has(k))headers.set(k,v);if(preview(request))headers.set('X-Robots-Tag','noindex, nofollow');let body=result?.body??'';if(headers.get('Content-Type')?.includes('text/html'))body=hardenHtml(body);if(request.method==='HEAD')body=null;return new Response(body,{status,headers});}
async function run(handler,request){try{return fromRouteResult(await handler(routeEvent(request)),request);}catch(error){console.error('Label by Zare Worker route failed:',error?.stack||error);return new Response('Service temporarily unavailable.',{status:503,headers:{...SECURITY,'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','Retry-After':'60'}});}}
function redirect(location,status=301){return new Response(null,{status,headers:{Location:location}});}
export default{async fetch(request,env,context){const url=new URL(request.url),path=url.pathname;const cached=handler=>publicDocument(request,context,()=>run(handler,request));const alias=path.match(/^\/(shop|sale|new-arrivals|search)(?:\.html|\/)$/);if(alias)return redirect('/'+alias[1]+url.search);if(path==='/index.html')return redirect('/'+url.search);if(!['GET','HEAD'].includes(request.method)){if(path==='/api/visitor-geo')return new Response('Method Not Allowed',{status:405,headers:{Allow:'GET, HEAD'}});return env.ASSETS.fetch(request);}if(path==='/api/visitor-geo')return visitorGeo(request);if(path==='/')return cached(homePage);if(path==='/shop'||path==='/sale'||path==='/new-arrivals'||path==='/search'||path.startsWith('/collections/'))return cached(collectionPage);if(path==='/journal'||path==='/journal/'||path.startsWith('/journal/'))return cached(journalPage);if(path==='/product'||path==='/product.html'||path.startsWith('/product/'))return cached(productPage);if(path==='/sitemap-pages.xml')return cached(sitemapPages);if(path==='/sitemap-products.xml')return cached(sitemapProducts);if(path==='/sitemap.html')return cached(sitemapHtml);if(path==='/product-feed.xml')return cached(productFeed);const asset=await env.ASSETS.fetch(request);if(/^\/(?:account(?:-login|-signup)?|admin(?:-activate)?|cart|checkout|wishlist|track-order|login|reset-password)(?:\.html|\/|$)/.test(path)){const headers=new Headers(asset.headers);headers.set('Cache-Control','private, no-store');headers.set('X-Robots-Tag','noindex, nofollow');return new Response(request.method==='HEAD'?null:asset.body,{status:asset.status,headers});}return asset;}};
