// Editorial pages contain general buying guidance. Product-specific claims belong
// in verified catalog fields; trade names are never treated as fibre composition.
const articles=[
 {slug:'choosing-an-abaya',title:'How to choose an abaya online',collection:'abayas',summary:'A thoughtful checklist for comparing silhouette, measurements, fabric details and the pieces included in your order.',sections:[
  ['Start with the way you will wear it','<p>An abaya for a regular commute may need a different sleeve shape or length from a piece chosen for an evening gathering. Start with your own routine: how much you walk, the shoes you wear, the layers underneath and the coverage you prefer. These details make a more useful starting point than a size label or a styled photograph alone.</p><p>Browse <a href="/collections/everyday-abayas/">everyday abayas</a> for your regular wardrobe, or the <a href="/collections/occasion-abayas/">occasion edit</a> for a celebration. The collection name is a browsing aid; the individual product details should guide your final choice.</p>'],
  ['Compare measurements, not just size names','<p>Measure a garment you already enjoy wearing on a flat surface. Compare its length, chest width and sleeve length with the measurements provided for the new piece, using the same measurement method. A relaxed cut can still feel restrictive at the upper arm or neckline.</p><p>Check the <a href="/support#size-guide">size guide</a> and ask for any missing garment measurements before ordering. Height alone cannot determine fit because body proportions, preferred coverage and footwear differ.</p>'],
  ['Read the fabric and included-item details','<p>Look for the stated material, lining, closure and care information. Names such as Nida, Korean Silk or Shamooz may be used as trade descriptions; do not assume a particular fibre percentage from the name. If composition matters to you, ask for the verified label or supplier specification.</p><p>Check whether a belt, inner dress or shawl is included. Accessories in styling photographs should only be considered part of the order when the description explicitly says so.</p>'],
  ['Look beyond one photograph','<p>Use the full gallery to inspect the front, back, sleeves and any detail photographs. Screen settings and lighting can change the appearance of a colour. If the exact shade is essential for an event, ask about the colour before placing your order rather than relying on a single image.</p><p>Finally, compare the price, available size and stock status, then read <a href="/support#shipping-returns">delivery and returns</a>. For a date-specific purchase, confirm that the delivery option serves your address and allows enough time.</p>'],
  ['A common question','<h3><span lang="ur-Latn">Abaya ka size kaise choose karein?</span></h3><p>Compare the product measurements with an abaya that fits you comfortably. Check the measurement method and ask us about any missing details before selecting a size. Our <a href="/journal/abaya-sizing-guide/">measuring guide</a> walks through the checks.</p>']
 ]},
 {slug:'everyday-abaya-guide',title:'An everyday abaya, chosen around your routine',collection:'everyday-abayas',summary:'Consider movement, layering and care before building your everyday wardrobe.',sections:[
  ['Begin with your day','<p>Think about where the garment will spend most of its time: at work, on campus, travelling or at home. Consider whether you carry a shoulder bag, use public transport or spend long periods seated. Check how the cut accommodates your usual layers and the movements you make throughout the day.</p><p>The <a href="/collections/everyday-abayas/">everyday collection</a> brings the current edit together. Use the product gallery and individual description to compare the actual details of each piece.</p>'],
  ['Check sleeves, closures and length','<p>Sleeve shape can affect practical comfort. A wider sleeve and a fitted cuff feel different when writing, handling a bag or adding a jacket. Check the available photographs and ask for a sleeve measurement if the detail is important to you.</p><p>Choose length with your usual footwear in mind. Compare with a well-fitting garment rather than estimating from a model photograph. If a style opens at the front, check the closure and whether you will need a separate inner layer.</p>'],
  ['Choose fabric using actual information','<p>Warm-weather comfort depends on more than a fabric name. Weight, weave, lining, fit and the layers underneath all matter. Read the material and care information attached to the specific product; request clarification where it is missing.</p><p>Do not assume that every piece described as Nida has the same weight, or that a trade name containing “silk” confirms pure silk. Our <a href="/journal/abaya-fabric-guide/">fabric buying guide</a> explains which questions to ask.</p>'],
  ['Build a small, useful combination','<p>Start with a colour you already wear regularly, then consider how it works with your shoes, bag and existing shawls. Repeating a familiar palette can make daily dressing simpler. Check whether an accompanying shawl is included before adding a separate piece.</p><p>Care requirements should fit your routine too. Follow the garment label, and ask for guidance before using heat or washing a piece with delicate trims. Compare the current <a href="/support#shipping-returns">delivery and return terms</a> before checkout.</p>'],
  ['A common question','<h3><span lang="ur-Latn">Rozana pehnne ke liye abaya kaise chunain?</span></h3><p>Start with fit, movement and the layers you usually wear. Compare sleeve shape, garment length and the stated care requirements, then choose the piece that fits your own day.</p>']
 ]},
 {slug:'occasion-abaya-styling',title:'Styling an occasion abaya with quiet confidence',collection:'occasion-abayas',summary:'Plan the silhouette, finishing touches and delivery timing for Eid, dinners and wedding gatherings.',sections:[
  ['Let the occasion guide the details','<p>An Eid visit, a dinner and a winter wedding gathering can each call for a different combination of layers, footwear and accessories. Begin with the setting and your preferred coverage. Then choose a silhouette that lets you move and sit comfortably through the event.</p><p>Explore the <a href="/collections/occasion-abayas/">occasion abaya edit</a> and look closely at each product’s actual finish. A collection label does not establish whether a design is suitable for a particular dress code; make that choice from the details and your own preferences.</p>'],
  ['Choose one point of interest','<p>If your chosen abaya has detailed sleeves or an embellished front, a simpler shawl and bag can leave those details visible. With a quieter silhouette, colour or texture in a finishing piece can become the focus. Compare the colours together in similar light where possible.</p><p>Check what the product price includes. A photographed belt, inner piece or shawl may be styling only. Use the description to confirm the included items before building the rest of the outfit.</p>'],
  ['Plan for movement and layers','<p>For a seated dinner, consider how the garment sits across the lap and whether the sleeves suit the setting. For cooler evenings, compare the fit with the layer you plan to wear underneath. The word “winter” alone cannot confirm warmth; fabric weight, lining and your layers all affect the result.</p><p>Check the <a href="/journal/abaya-sizing-guide/">measurement guide</a>, including garment length with your intended shoes. If you require an alteration, ask about feasibility before ordering; do not assume tailoring is included.</p>'],
  ['Order around a confirmed timeline','<p>For Eid, Ramadan evenings or a wedding date, check the current stock and delivery details early. Religious festival dates can depend on local moon-sighting announcements. Do not use an estimated calendar date as a guaranteed dispatch or delivery deadline.</p><p>Processing time and transit time are separate. Read our <a href="/support#shipping-returns">delivery information</a> and confirm service to your address if timing is tight. Keep the purchase decision grounded in the current product listing, rather than an old social post.</p>']
 ]},
 {slug:'kaftan-fit-guide',title:'Choosing the right kaftan silhouette',collection:'kaftans',summary:'A relaxed shape still needs the right length, width and sleeve proportions.',sections:[
  ['Understand the shape before selecting a size','<p>Kaftan designs vary in width, sleeve construction, neckline and length. A loose appearance in a photograph does not tell you how much room a particular size provides. Begin with the measurements of the specific design in the <a href="/collections/kaftans/">kaftan collection</a>.</p><p>Compare the garment with something you already wear comfortably. Ask whether a listed width is measured flat or around the body; those numbers are not interchangeable. Do not assume a one-size label will fit every body or every preferred silhouette.</p>'],
  ['Check where the fabric falls','<p>Look at the side and back photographs as well as the front. Notice where the sleeve meets the body, whether a belt changes the silhouette and how much of the shape comes from styling. If a belt is pictured, confirm that it is included.</p><p>Consider how the neckline, arm opening and side openings work with your preferred coverage. You may choose an inner layer depending on the design, but it should not be assumed to come with the garment unless listed.</p>'],
  ['Match the length to the way you dress','<p>Choose the length with your usual shoes or the footwear planned for the occasion. Compare from the same measurement point used by the seller, rather than estimating from the model’s height.</p><p>If you plan to sit, drive or walk frequently, assess the cut around those movements. A generous body width does not automatically provide the sleeve or upper-arm fit you need.</p>'],
  ['Read the material and care information','<p>Fluid-looking fabric is a visual characteristic, not proof of a particular composition. Check the actual material notes. Where a listing uses a trade name such as Korean Silk or Shamooz, ask for verified composition if it will affect your choice.</p><p>Follow the care label and ask before applying heat to decorative details. The <a href="/journal/abaya-fabric-guide/">fabric and care guide</a> provides a practical checklist. Before checkout, confirm size availability and review the current delivery and return terms.</p>']
 ]},
 {slug:'prayer-abaya-guide',title:'Choosing a prayer piece for your own routine',collection:'prayer-abayas',summary:'Compare coverage, movement, included pieces and care details with your preferences in mind.',sections:[
  ['Start with your preferred coverage','<p>A prayer piece should be assessed by its actual design and your own coverage preferences. Check the neckline, sleeve opening and garment length in the photographs and description. The category name alone does not establish that a design meets every individual’s requirements.</p><p>Our <a href="/collections/prayer-abayas/">prayer edit</a> brings the available pieces together. If an important detail is unclear, ask for a measurement or additional product information before ordering. This guide concerns clothing selection; it does not provide religious rulings.</p>'],
  ['Consider movement as well as standing fit','<p>Compare how much room you prefer through the shoulders, arms and body. A garment that looks long while standing may sit differently when moving. Use a piece you already find comfortable as a measurement reference.</p><p>Check whether the sleeves stay where you want them and whether the neckline works with the head covering you plan to wear. Avoid making the decision from height or an S, M or L label alone.</p>'],
  ['Confirm exactly what is included','<p>Read whether the listing contains a single garment or a set, and whether a head covering, skirt or storage pouch is actually included. Do not infer the contents from a styled image.</p><p>Consider your intended layers when comparing fabric information. Opacity can vary with lighting, stretch and what is worn underneath. Ask about lining or additional details instead of treating a fabric name as a guarantee.</p>'],
  ['Make care part of the choice','<p>For a frequently worn piece, check the care instructions before buying. Follow the garment label and seek clarification if there is no published guidance. An easy-looking fabric should not automatically be treated as machine washable.</p><p>If ordering before Ramadan or as a gift, allow for the stated processing and delivery times. Check the current <a href="/support#shipping-returns">return conditions</a> and keep tags attached while assessing the fit.</p>'],
  ['A common question','<h3><span lang="ur-Latn">Namaz ke liye abaya kaise choose karein?</span></h3><p>Compare the length, neckline and sleeves with your preferred coverage, including when moving. Read which items are included and ask us about any measurements or design details you need before ordering.</p>']
 ]},
 {slug:'shawl-pairing-guide',title:'Pairing a shawl with your abaya',collection:'shawls',summary:'Choose colour, dimensions and texture as a considered finishing touch.',sections:[
  ['Begin with the pieces you already own','<p>Look at the abayas, kaftans and outer layers you wear most often. A shawl in a familiar colour can create a quiet combination; a contrasting shade can become the focus. There is no single required palette—start with what you enjoy wearing.</p><p>Browse the <a href="/collections/shawls/">shawl collection</a> for the current selection. The edit may be empty between releases. Product availability and prices appear on the individual listings when pieces are available.</p>'],
  ['Use dimensions to understand the drape','<p>The length and width affect the ways you can wrap or arrange a shawl. Compare the stated dimensions with a piece you already own, rather than judging size from a styled photograph. Ask for missing measurements if a particular wrapping style matters to you.</p><p>Consider the neckline and sleeve details of the abaya underneath. A simple arrangement can leave an embellished neckline visible, while a fuller wrap changes the overall silhouette.</p>'],
  ['Read texture and colour carefully','<p>Photographs can help you assess a surface finish, but cannot fully establish softness, weight or warmth. Check the stated composition and care details. Ask for clarification when a trade name is the only material information.</p><p>Compare colours in similar light where possible. Screens and studio lighting can make a shade appear warmer, cooler or more saturated. If matching an existing outfit precisely, contact us before placing the order.</p>'],
  ['Check the listing before checkout','<p>A shawl sold as a separate product does not include a styled abaya unless the description explicitly lists it. The same applies in reverse: a shawl shown with an abaya may be styling rather than part of a set.</p><p>Follow the care label and handle delicate trims with care. For a complete outfit, compare <a href="/collections/abayas/">abayas</a> alongside the shawl details and review the current <a href="/support#shipping-returns">delivery and return information</a>.</p>']
 ]},
 {slug:'abaya-fabric-guide',title:'An honest guide to abaya fabric names and care',collection:'abayas',summary:'What to ask when a listing mentions Nida, Korean Silk, Shamooz or organza.',sections:[
  ['Separate the name from the specification','<p>Fabric descriptions are a useful starting point, but a name on its own may leave important questions unanswered. Read the product’s stated composition, lining and care information together. If a specification is missing, ask for a verified answer before buying.</p><p>In particular, do not treat a trade name containing “silk” as confirmation of a pure silk fibre composition. Label by Zare’s product pages should be read for the details of that individual piece, rather than assumptions about an entire collection.</p>'],
  ['Questions worth asking','<table><thead><tr><th>Description you may see</th><th>What to confirm</th></tr></thead><tbody><tr><td>Nida</td><td>The verified fibre composition, weight or feel, lining and care instructions for this piece.</td></tr><tr><td>Korean Silk</td><td>Whether this is a trade description; ask for the stated fibre percentages rather than assuming silk content or country of manufacture.</td></tr><tr><td>Shamooz / charmeuse</td><td>The composition and surface finish, plus any lining and care requirements.</td></tr><tr><td>Organza</td><td>The composition, which parts of the garment use it, and whether those areas are lined.</td></tr></tbody></table><p>Two garments using the same descriptive name need not have identical weight, finish or care needs. Choose using the specific listing and verified information.</p>'],
  ['Assess opacity and comfort in context','<p>Opacity depends on the particular fabric and construction, as well as lighting and the layers worn underneath. Ask about lining and examine the actual gallery. A dark colour or a familiar material name should not be treated as a guarantee.</p><p>Likewise, comfort in warm or cool weather depends on your fit, layers, environment and the garment’s construction. We do not assign a universal summer or winter performance rating from a trade name.</p>'],
  ['Let the care label lead','<p>Follow the garment’s care label. If instructions are missing or unclear, contact the seller before washing, ironing or using stain-removal products. Trims, lining and embellishments can require different care from the main fabric.</p><p>Do not test high heat or a cleaning chemical on a visible part of the garment. If specialist cleaning is indicated, show the care label and explain any decorative details to the cleaner. Store the piece clean and dry, with the method suited to its label and construction.</p><p>Ready to compare designs? Explore <a href="/collections/everyday-abayas/">everyday abayas</a>, <a href="/collections/occasion-abayas/">occasion wear</a> and <a href="/collections/kaftans/">kaftans</a>.</p>']
 ]},
 {slug:'abaya-sizing-guide',title:'How to measure before ordering an abaya',collection:'abayas',summary:'Compare garment measurements carefully, and know which details to confirm before selecting a size.',sections:[
  ['Choose a reliable reference garment','<p>Take an abaya or a similar garment that fits the way you like. Lay it flat without stretching the fabric, close it as you normally wear it and smooth out folds. Use a flexible measuring tape and write down the units.</p><p>Check the seller’s measurement method before comparing. A flat garment width, a full garment circumference and a body measurement are three different things. If the listing does not state which it uses, ask before ordering.</p>'],
  ['Compare the details that affect fit','<ul><li><strong>Length:</strong> use the same starting point as the product size guide. Consider the shoes you plan to wear.</li><li><strong>Chest and body width:</strong> compare the published garment measurement with your reference garment, allowing for your preferred ease and layers.</li><li><strong>Sleeve length and opening:</strong> check both reach and the room you prefer around your arm or wrist.</li><li><strong>Shoulders and neckline:</strong> confirm any missing measurements that matter for the cut you are considering.</li></ul><p>Some silhouettes have dropped shoulders or integrated sleeves, so a measurement taken from a different starting point may mislead. Request the method as well as the number.</p>'],
  ['Treat labels as a starting point','<p>A size called Medium in one design can differ from Medium in another. A one-size kaftan also has actual dimensions and limits. Choose using the individual design rather than a letter or your height alone.</p><p>See the published <a href="/support#size-guide">size guide</a>, then compare the product’s own information. If the guide and listing appear inconsistent, ask us to confirm before checkout. Do not average conflicting measurements.</p>'],
  ['Ask a precise question when unsure','<p>Tell us which product and size you are considering, which garment measurement you need and whether you mean a flat width or a circumference. You can also describe the fit you prefer without sharing personal information you do not wish to provide.</p><p>Before buying for a fixed date, confirm stock and delivery timing. When your order arrives, review the <a href="/support#shipping-returns">return conditions</a> before wearing or removing tags.</p>'],
  ['A common question','<h3><span lang="ur-Latn">Meri height ke liye konsa abaya size theek hai?</span></h3><p>Height helps you think about length, but it does not determine the full fit. Compare garment length, body width and sleeves with a piece you already wear comfortably, using the same measurement method.</p>']
 ]}
];
const Catalog=require('./catalog');
function normalize(row){
  if(!row) return null;
  const sections=Array.isArray(row.sections)?row.sections.map(section=>Array.isArray(section)?section:[section.heading||'',section.body||'']):[];
  return {slug:row.slug,title:row.title,collection:row.collection||'abayas',summary:row.summary||'',sections};
}
async function list(){
  try{
    const rows=await Catalog.request('journal_articles?select=slug,title,collection,summary,sections,sort_order&active=eq.true&order=sort_order.asc,slug.asc',{timeoutMs:2500});
    if(Array.isArray(rows)&&rows.length) return rows.map(normalize).filter(Boolean);
  }catch(error){ console.warn('Journal CMS unavailable; using bundled guides.',error?.message||error); }
  return articles;
}
async function getLive(slug){
  try{
    const rows=await Catalog.request(`journal_articles?slug=eq.${encodeURIComponent(slug)}&active=eq.true&select=slug,title,collection,summary,sections&limit=1`,{timeoutMs:2500});
    if(Array.isArray(rows)&&rows[0]) return normalize(rows[0]);
  }catch(error){ console.warn('Journal CMS lookup unavailable; using bundled guide.',error?.message||error); }
  return articles.find(a=>a.slug===slug)||null;
}
module.exports={articles,get:slug=>articles.find(a=>a.slug===slug),list,getLive};
